[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


# pytest recommends storing settings in this file (not setup.cfg)
[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["src"]
